
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Maps Apache to localhost:8080
    volumes:
      - .:/var/www/html
    env_file:
      - .env                # Load environment variables from the .env file

    networks:
      - trnty

    depends_on:
      - db
    command: /bin/sh -c "/usr/local/bin/wait-for-it db:3306 -- composer install  && apache2-foreground"

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}    # Loaded from .env
      MYSQL_DATABASE: ${DB_DATABASE}              # Loaded from .env
      MYSQL_USER: ${DB_USERNAME}                  # Loaded from .env
      MYSQL_PASSWORD: ${DB_PASSWORD}              # Loaded from .env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - trnty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80" # phpMyAdmin on localhost:8081
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}    # Loaded from .env
    networks:
      - trnty

volumes:
  dbdata:

networks:
  trnty:
    driver: bridge
